baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Application Modernization Cookbook"
copyright = "@2020, Pivotal VMware Software, Inc. All Rights Reserved, Confidential"
theme = "hugo-theme-docdock"
publishDir = "public"
pygmentsCodeFences = true
pygmentsStyle = "friendly"
enableRobotsTXT = true
enableGitInfo = true

[params]
  themeStyle = "original"
  disableHomeIcon = true
  description = "Migrating applications"
  noCategoryLink = true
  showVisitedLinks = false
  noSearch = false
  noHomeIcon = true
  ordersectionsby = "weight"
  ignoreFiles = [ "\\.adoc$" ]
  disableNavChevron = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h5>&nbsp;</h5>"
name = "<i class='fa fa-tag'></i>  See All Tags"
url = "/tags"
